# Site settings
author: blessed-mouse-7746
title: 
header-img: img/home-bg.png
email: nyabutijoash@yahoo.com
copyright_name: blessed-mouse-7746
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: NJoash
github_username:  me-and-ruby

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
